### ISSUE TITLE
AUR Package release

### ISSUE THREAD

**Issue by Sinasta** [limads/queries#2]
First of all thank you for this project.
I wanted to inquire if a possible AUR package is in planning?

**Comment by limads** [comment]
Hello, I'm unfamiliar with AUR distribution process/policies. All I can manage for the short-term future are Flatpak releases. But I'm not opposed to other distribution channels in the future.

**Comment by Sinasta** [comment]
Thank you for your answer. Sadly i dont know enough to be of any help for AUR packaging.
